Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/eventmanager/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/1/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `event` is not valid for model `Client`.
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/1//events/
Not Found: /clients/1//events/
Internal Server Error: /clients/1/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 202, in get_queryset
    return Event.objects.filter(contract_id=self.kwargs['contract_pk'])
KeyError: 'contract_pk'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/1/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 202, in get_queryset
    return Event.objects.filter(contract_id=self.kwargs['contract_id'])
KeyError: 'contract_id'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /users/
Bad Request: /users/
Unauthorized: /users/
Unauthorized: /users/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 46, in update
    username=validated_data['username'],
KeyError: 'username'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password"]):
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password"]):
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password"]):
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password"]):
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 45, in update
    if validated_data["password"]:
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password"]):
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password"]):
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password"]):
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password_confirmation"]):
KeyError: 'password_confirmation'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /users/6/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py", line 22, in validate
    (self.context['request']._request.method == 'PATCH' and data["password"]):
KeyError: 'password'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /users/10/
Forbidden: /users/
Bad Request: /users/
Bad Request: /users/9/
Unauthorized: /login/
Not Found: /clients/2/
Bad Request: /clients/
Not Found: /clients/1/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/<integer>/contracts/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '<integer>'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 131, in get_queryset
    return Contract.objects.filter(client_id=self.kwargs['client_pk'], sales_contact=self.request.user)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '<integer>'.
Internal Server Error: /clients/5/contracts/10/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `event_id` is not valid for model `Contract`.
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/5/contracts/10/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `event` is not valid for model `Contract`.
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/serializers.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/5/events/19/
Not Found: /clients/5/events/19/
Internal Server Error: /clients/<integer>/contracts/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '<integer>'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 131, in get_queryset
    return Contract.objects.filter(client_id=self.kwargs['client_pk'], sales_contact=self.request.user)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '<integer>'.
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/5/events/23/
Internal Server Error: /clients/<integer>/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '<integer>'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 202, in get_queryset
    return Event.objects.filter(client_id=self.kwargs['client_pk'])
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '<integer>'.
Forbidden: /clients/5/events/
Forbidden: /clients/5/events/
Internal Server Error: /clients/<integer>/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '<integer>'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 202, in get_queryset
    return Event.objects.filter(client_id=self.kwargs['client_pk'])
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '<integer>'.
Bad Request: /clients/5/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/5/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/5/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/5/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/5/events/
Bad Request: /clients/5/events/
Bad Request: /clients/5/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/5/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/5/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/1/events/
Internal Server Error: /clients/1/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "client_id" of relation "crm_api_event" violates not-null constraint
DETAIL:  Failing row contains (21, Marriage anniversary, A huge anniversary, 32, T, 2023-06-20 11:30:00+00, 2023-01-26 17:20:24.922733+00, 2023-01-26 17:20:24.922747+00, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 217, in perform_create
    serializer.save(support_contact=None)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "client_id" of relation "crm_api_event" violates not-null constraint
DETAIL:  Failing row contains (21, Marriage anniversary, A huge anniversary, 32, T, 2023-06-20 11:30:00+00, 2023-01-26 17:20:24.922733+00, 2023-01-26 17:20:24.922747+00, null, null, null).

/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/1/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "client_id" of relation "crm_api_event" violates not-null constraint
DETAIL:  Failing row contains (22, Marriage anniversary, A huge anniversary, 32, T, 2023-06-20 11:30:00+00, 2023-01-26 17:21:42.661392+00, 2023-01-26 17:21:42.661403+00, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 218, in perform_create
    serializer.save(support_contact=None)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "client_id" of relation "crm_api_event" violates not-null constraint
DETAIL:  Failing row contains (22, Marriage anniversary, A huge anniversary, 32, T, 2023-06-20 11:30:00+00, 2023-01-26 17:21:42.661392+00, 2023-01-26 17:21:42.661403+00, null, null, null).

Internal Server Error: /clients/1/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "client_id" of relation "crm_api_event" violates not-null constraint
DETAIL:  Failing row contains (23, Marriage anniversary, A huge anniversary, 32, T, 2023-06-20 11:30:00+00, 2023-01-26 17:23:22.281777+00, 2023-01-26 17:23:22.281793+00, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 218, in perform_create
    serializer.save(support_contact=None)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "client_id" of relation "crm_api_event" violates not-null constraint
DETAIL:  Failing row contains (23, Marriage anniversary, A huge anniversary, 32, T, 2023-06-20 11:30:00+00, 2023-01-26 17:23:22.281777+00, 2023-01-26 17:23:22.281793+00, null, null, null).

/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/1/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "contract_id" of relation "crm_api_event" violates not-null constraint
DETAIL:  Failing row contains (24, Marriage anniversary, A huge anniversary, 32, T, 2023-06-20 11:30:00+00, 2023-01-26 17:24:16.465676+00, 2023-01-26 17:24:16.465692+00, 1, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 217, in perform_create
    serializer.save(support_contact=None, client_id=self.kwargs['client_pk'])
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "contract_id" of relation "crm_api_event" violates not-null constraint
DETAIL:  Failing row contains (24, Marriage anniversary, A huge anniversary, 32, T, 2023-06-20 11:30:00+00, 2023-01-26 17:24:16.465676+00, 2023-01-26 17:24:16.465692+00, 1, null, null).

/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/5/events/
Bad Request: /clients/1/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/5/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/1/events/
Not Found: /clients/1/events/26/
Bad Request: /clients/1/events/26/
Internal Server Error: /clients/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 69, in get_queryset
    contract__in=Contract.objects.filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'event' into field. Choices are: amount, client, client_id, contract_event, date_created, date_updated, id, payment_due, sales_contact, sales_contact_id, signed
Internal Server Error: /clients/1/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 69, in get_queryset
    contract__in=Contract.objects.filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'event' into field. Choices are: amount, client, client_id, contract_event, date_created, date_updated, id, payment_due, sales_contact, sales_contact_id, signed
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/1/contracts/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 131, in get_queryset
    return Contract.objects.filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'event' into field. Choices are: amount, client, client_id, contract_event, date_created, date_updated, id, payment_due, sales_contact, sales_contact_id, signed
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/1/contracts/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 216, in _queryset
    assert queryset is not None, (
AssertionError: ContractViewset.get_queryset() returned None
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/1/contracts/
Bad Request: /clients/1/contracts/5/
Bad Request: /clients/<integer>/contracts/
Bad Request: /clients/<integer>/contracts/<integer>/
Bad Request: /clients/1/contracts/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/1/events/
Bad Request: /clients/1/events/<integer>/
Bad Request: /clients/1/events/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clients/1/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 232, in has_permission
    queryset = self._queryset(view)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/permissions.py", line 215, in _queryset
    queryset = view.get_queryset()
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 192, in get_queryset
    elif self.request.user.role == "SA" and self.request.action != "POST":
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'action'
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /clients/1/events/
Bad Request: /clients/1/events/<integer>/
Bad Request: /clients/1/events/
Bad Request: /clients/1/events/12/
Bad Request: /clients/5/events/
Internal Server Error: /clients/5/events/
Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2018, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '{{eventContractId}}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py", line 204, in perform_create
    contract = get_object_or_404(Contract, pk=contract_id)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/bricevenayre/.local/share/virtualenvs/P12_epicevents-LJlfhQ_f/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2020, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '{{eventContractId}}'.
Bad Request: /clients/5/events/
Bad Request: /clients/5/events/
Not Found: /clients/5/events/
Bad Request: /clients/5/events/
Not Found: /clients/4/
Not Found: /clients/5/
Not Found: /clients/5/
Bad Request: /clients/5/
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bricevenayre/Documents/Work/Open Classrooms/P12_epicevents/src/crm_api/views.py changed, reloading.
Watching for file changes with StatReloader
